### ISSUE TITLE
artwork

### ISSUE THREAD

**Issue by patte** [orbiting/app#10]
- [x] integrate artwork
- [x] provide a list with all required artworks (icons, splashscreens) including the expected file-formats and sizes.
- [ ] let the design-team check all integrated artworks

**Comment by diegomura** [comment]
## Current artwork

### Icons

| Image        | Name           | Description  |
| ------------- |:-------------:| -----:|
| <img width="150" alt="audio" src="https://user-images.githubusercontent.com/5600341/42765422-632bc4dc-88ee-11e8-884e-fd6cb03e209a.png"> | audio.png | Audio feature icon |
| <img width="150" alt="chevron-down" src="https://user-images.githubusercontent.com/5600341/42765566-b46ff840-88ee-11e8-92d6-3efd606c447e.png"> | chevron-down.png | Down arrow for header menus |
| <img width="150" alt="chevron-up" src="https://user-images.githubusercontent.com/5600341/42765618-cdce587c-88ee-11e8-8b5c-fcfb8d21d580.png"> | chevron-up.png | Up arrow for header menus |
| <img width="150" alt="close" src="https://user-images.githubusercontent.com/5600341/42765636-db588684-88ee-11e8-9a9c-82f54284f643.png"> | close.png | Close menu icon |
| <img width="150" alt="discussion" src="https://user-images.githubusercontent.com/5600341/42765677-f12358ea-88ee-11e8-8881-563cd853f72f.png"> | discussion.png | Discussion header icon |
| <img width="150" alt="pause" src="https://user-images.githubusercontent.com/5600341/42765715-03f61976-88ef-11e8-8f4b-7f7417618192.png"> | pause.png | Pause icon on audio player  |
| <img width="150" alt="pdf" src="https://user-images.githubusercontent.com/5600341/42765765-1d835dfe-88ef-11e8-8d99-1b41262d60c6.png"> | pdf.png | PDF header icon |
| <img width="150" alt="play" src="https://user-images.githubusercontent.com/5600341/42765791-2aca439c-88ef-11e8-94eb-3f4687aefa7a.png"> | play.png | Play icon on audio player |
| <img width="150" alt="profile-placeholder" src="https://user-images.githubusercontent.com/5600341/42765812-39e84de2-88ef-11e8-97d2-240852cb24fd.png"> | profile-placeholder.png | Profile picture placeholder for header |
| <img width="150" alt="share" src="https://user-images.githubusercontent.com/5600341/42765867-5d1f45cc-88ef-11e8-9d84-dcac5fbca340.png"> | share.png | Share menu icon |
| <img width="150" alt="profile-icon" src="https://user-images.githubusercontent.com/5600341/42765899-703d58f6-88ef-11e8-8da7-d517cc9a8f7e.png"> | profile-icon.png | Profile icon for header when user not logged in |
| <img width="150" alt="search" src="https://user-images.githubusercontent.com/5600341/42765941-8e0a8106-88ef-11e8-928c-aa44ffe091c9.png"> | search.png | Inactive header search icon |
| <img width="150" alt="search-active" src="https://user-images.githubusercontent.com/5600341/42765940-8dbfbb08-88ef-11e8-9562-c8a680fb76b8.png"> | search-active.png | Active header search icon |
