### ISSUE TITLE
splash screen is streched on android

### ISSUE THREAD

**Issue by patte** [orbiting/app#102]
![img_2687](https://user-images.githubusercontent.com/3500621/43231217-b4fce2bc-906b-11e8-99cc-c66b027ba36c.jpg)

**Comment by diegomura** [comment]
Oh wow.
Do you know which device/ android version are you running there?

**Comment by diegomura** [comment]
Good catch. This was an issue on SDK 22 and below. Was a good thing you tested it in an old device after all
