### ISSUE TITLE
native audio player is missing the pause icon (on android)

### ISSUE THREAD

**Issue by patte** [orbiting/app#104]
The play icon shows as it should, but as soon as the player is playing I would expect a pause icon to show, as it does on iOS. Only tested on one device with android 5.2.
Related:
- It would be handy if the native player would show the title of the playing article
- when taping on the native player I would expect to be navigated to the playing article

![screenshot_2018-07-26-02-15-31](https://user-images.githubusercontent.com/3500621/43234179-e37a6aa6-907a-11e8-825d-d7ba26fcbfa1.png)
![screenshot_2018-07-26-02-15-42](https://user-images.githubusercontent.com/3500621/43234180-e391b12a-907a-11e8-9a19-fb99d7f1d3c2.png)

**Comment by diegomura** [comment]
Couldn't replicate the pause icon issue. Always shows. This is android 5.1 running in emulator:
![screenshot_1532624139](https://user-images.githubusercontent.com/5600341/43276635-bce2175c-90db-11e8-9fa3-f4321ce31ddb.png)

@patte What are the specs of the emulator you used? Device, SDK, etc
I also tried with other SDKs version, and always shows
