### ISSUE TITLE
Frontend menu on Android 5.1

### ISSUE THREAD

**Issue by diegomura** [orbiting/app#109]
This is what I see on the emulator.
For some reason, the layout is not being show correctly:

![screenshot_1532627484](https://user-images.githubusercontent.com/5600341/43279108-6fa2ed60-90e3-11e8-9b5a-3ee8c51ad06b.png)

@patte you didn't experience this when you tested the app in your old device?

**Comment by patte** [comment]
No I never encountered this problem. But it just seems that the footer in the menu is too large, just some css magic needed. I see who can get this done if you don't want to fiddle around with it ;)

**Comment by diegomura** [comment]
Awesome. Thanks. 
I can do it eventually, but now prioritizing auth stuff

**Comment by diegomura** [comment]
Fixed [here](https://github.com/orbiting/republik-frontend/pull/113/commits/d16d6f4b2fbe476a5ca0c8b9989ce51d67910a56) and [here](https://github.com/orbiting/republik-frontend/pull/113/commits/06f21de330ae3c1d0da04e6e939673e78f6f2f94)
