### ISSUE TITLE
refactor signIn by app (user interaction)

### ISSUE THREAD

**Issue by patte** [orbiting/app#118]
We did some serious user testing to see if the sign-in-by-app mechanism is userfriendly enough. Despite other findings it became clear that many users miss the initial display of the notification on the iPhone and most of the don't search for it in the notification center afterwards, but they just open the app and expect to see the request there in able to confirm it. This actually makes sense, if you get a notification by slack/gmail it's natual to just open the corresponding app and expect to see the news there.

We discussed this problem internally and came up with two possible ways to solve the problem.
1. Show a green lock icon in the header (next to the profile image). If a `authorize` notification was sent less than 10mins ago that wasn't yet opened. When tipping on the icon, the auth screen should appear.
2. Don't even bother with an icon: Just open the auth screen if the app come's from background and there is an "unresolved" auth request.

I would like to know what you think @diegomura

**Comment by diegomura** [comment]
I like the idea. I think is the way to go. 
Not sure about the green lock icon though. It's not very descriptive. I would go with opening the modal directly, or with a banner (green background maybe?) saying that you have an authorization request, and when clicked the modal is displayed. I like this idea a lot.

However, this brings a technical issue: if user is in background, there's no callback called that enables me to open modal when user re-opens the app. There is one when notification clicked. If app in foreground, there's no problem at all. So I guess here what we should do is querying a graphql endpoint directly from the app, and identifying if there is a valid request

**Comment by patte** [comment]
I thought about it and I think we should do both ;) Meaning:
- open the auth screen if the was an notification, but only once. If the user clicks it away, then goes to background/foreground it doesn't open a second time
- but the green lock icon would stick in the navbar until expireAt
So in general the user would get 3 changes: 1. click on the notification, 2. open the app, 3. click on the lock. The redundant ways seem appropriate having watched inexperienced users and should not be annoying for pro-users at the same time I think.

True. That would be a way, adding a query where you could get "unattended" and unexpired tokens. I thought about doing it like this in the first place. It's a different security model tough: instead of delivering a token you have to get to authenticate a new session, it would allow every existing session to do so. Actually I think that could be a cool feature on the desktop in the future. But right now, I think we should only allow the app to do this, as it's considered a more secure and personal device in comparison to all other places you might signIn and because it's easier to explain to our clients and we don't have the time to also realize it on the desktop. Do you agree? @diegomura @tpreusse
