### ISSUE TITLE
review back action on iOS

### ISSUE THREAD

**Issue by patte** [orbiting/app#119]
during user tests, many struggled to find the way to "go back" under iOS. They missed the back button, like it exists in safari.
I currently see some ways out of this:
- Start the app with a tutorial that explains and let users try the swipe-back gesture (design and interaction heavy)
- Show an additional bar on the bottom with a back button, copying the slide-in/-out behaviour of safari. This would conflict with the audioplayer tough.
- Add a back button the the subnav. This is also less than ideal because it would shift the content off center, making everything ugly.

Does someone have a better idea please? :) @diegomura @tpreusse

**Comment by diegomura** [comment]
🤔 tricky scenarios all of them.
iOS back button is generally on the left corner of the top native header. What about replacing the user avatar with a back button when back is enabled? I know this could break the design a bit, but it's the more natural way of doing it.

Another way could be adding the back in a bottom nav, and moving the audio player maybe to the subnav, but that would also feel weird a bit.

**Comment by tpreusse** [comment]
After discussion with @patte:
Let's replace the profile picture with the back arrow on iOS if the path is not the overview pages (subnav linked pages -> `['/', '/feed', 'rubriken']`). Also keep the back button around when scrolling down and showing the share button.
