### ISSUE TITLE
app authenticator

### ISSUE THREAD

**Issue by patte** [orbiting/app#12]
Our users experience quite some problems with the passwordless-email signin e.g. emails take to long to arrive, get dumped into the spam folder or don't arrive at all. Once a user has signed in via email in the app, the app could act as an authenticator, authorizing future signin requests from other devices, thus skipping the email path completely.
Detailed tasks have to be defined.

**Comment by diegomura** [comment]
Includes #22

**Comment by patte** [comment]
see:
- https://github.com/orbiting/backends/pull/69
- https://github.com/orbiting/republik-frontend/pull/139
