### ISSUE TITLE
cookie in WKWebView (cookie echo portal)

### ISSUE THREAD

**Issue by patte** [orbiting/app#147]
Only having cookies in NSHTTPCookieStorage not inside the WKWebView still causes problems.

To get around the problem without [WKHTTCookieStore](https://stackoverflow.com/questions/26573137/can-i-set-the-cookies-to-be-used-by-a-wkwebview), which is iOS 11+ only, we can rely on WKWebView setting/remembering the cookie to itself if it's set as `Set-Cookie` header on a response to a request it fired.
Fortunately initial requests the WKWebView sends are augmented with the cookie out of NSHTTPCookieStorage by [react-native-wkwebview](https://github.com/CRAlpha/react-native-wkwebview). Unfortunately tough the only requests the WKWebView sends are going to republik-frontend right now, which indeed forwards this cookie to the backend, but doesn't proxy back `Set-Cookie` from the backend. 
The idea I tested, is that the app, after it successfully got the cookie into NSHTTPCookieStorage through signIn with the react-native apollo-link, it switches WKWebView's source to `http://api.republik.whatever/cookie-portal?url=http://republik.whatever`. The handler of this route responds with a redirect to `?url=` including `Set-Cookie` on it's response. I call this method: the cookie echo portal 🍪☄️. It has the advantage that the frontend can continue ignoring cookies.
To test the success I added a primitive fetch to the Front.

Test it:
- add `COOKIE_PORTAL_URL=http://localhost:5000/cookie-portal` to the app's `.env.dev` and to republik-frontend's `.env`
- checkout the following branches:
  - backends: app-cookie-portal
  - frontend: app-cookie-portal
  - app: cookie-portal
- boot the app in a fresh iOS simulator, signIn, go to front, check the console in safari and the console of the backend. Be amazed by authenticated fetch calls from frontend client-side js.

https://github.com/orbiting/backends/compare/app...app-cookie-portal
https://github.com/orbiting/app/compare/cookie-portal
https://github.com/orbiting/republik-frontend/compare/app...app-cookie-portal

I think this can be further refined with better knowledge about all the app-bridge magic. Interested in your comments: @tpreusse @diegomura

**Comment by tpreusse** [comment]
Solved with FE cookie forward solution: https://github.com/orbiting/republik-frontend/pull/161
