### ISSUE TITLE
Test Over-The-Air-Update (OTA)

### ISSUE THREAD

**Issue by tpreusse** [orbiting/app#151]
After updating the app via test flight it kept crashing and updating to an older JS bundle published via OTA.

Updating to the older JS bundle might be technically correct because the binary version was not bumped. At the same time it should probably detect that it ships with a newer bundle and not update.

Additionally it is unclear why it crashed. Wasn't able to extract logs.

**Comment by ovbm** [comment]
@tpreusse is this still relevant?

**Comment by tpreusse** [comment]
nope, we've removed OTA
