### ISSUE TITLE
Unregister Device on Uninstall

### ISSUE THREAD

**Issue by tpreusse** [orbiting/app#161]
## Bug Report

When the app is deleted without signing out the session stays active and pushs are sent that never arrive.

**Steps to Reproduce**

1. Login in app
2. Uninstall app

**Actual Results**

The sign in request continue to be sent as push notification even though no receiving device has a logged in app installed.

**Expected Results**

Sign out is somehow triggered. Maybe there is a delete hook? Or when sending the notification Apple/Google may report back that it can't be delivered.

**Environment**

- OS: all
- App Version: all

**Possible Solutions**

- delete hook
- notification sent statuses

**Comment by garamond** [comment]
**Proposed solution for iOS**

Response ~16 hours after uninstalling app:

```
{
    "failed": [
        {
            "device": "f122bf584c11e7905eb53faec2ba0f13233cad700acb4da81a22e4eeebab5a35",
            "response": {
                "reason": "Unregistered",
                "timestamp": 1542743186255
            },
            "status": "410"
        }
    ],
    "sent": []
}

```

The session matching the device ID can simply be cleared.

**Comment by garamond** [comment]
**Proposed solution for Android**

Response immediately after uninstalling the app:

```
{
    "error": {
        "code": "messaging/registration-token-not-registered",
        "message": "The provided registration token is not registered. A previously valid registration token can be unregistered for a variety of reasons. See the error documentation for more details. Remove this registration token and stop using it to send messages."
    }
}
```

The token itself is not returned with the error. However, according to [the docs](https://firebase.google.com/docs/cloud-messaging/http-server-ref#interpret-downstream):

> Array of objects representing the status of the messages processed. The objects are listed in the same order as the request (i.e., for each registration ID in the request, its result is listed in the same index in the response).

Therefore, we should retrieve them from the input array and clear the corresponding sessions.

**Comment by garamond** [comment]
Needs more testing, removing from Milestone 1
