### ISSUE TITLE
Fix RollDeviceToken

### ISSUE THREAD

**Issue by tpreusse** [orbiting/app#162]
## Bug Report

RollDeviceToken is reported as 100% failure rate (based on over 500 requests) on the backend.

Error message in the backend:
```
graphql error in undefined (undefined): { GraphQLError: Variable "$oldToken" got invalid value null; Expected non-nullable type String! not to be null.
```

**Steps to Reproduce**

_unclear_

**Actual Results**

Seems to not send an oldToken.

**Expected Results**

Should send an oldToken.

**Environment**

- OS: Android
- App Version: 1.0.1/1.0.2

**Comment by garamond** [comment]
This is unexpected, since there is an explicit check before the mutation is invoked. Rollover works fine when I test it locally.
