### ISSUE TITLE
Universal Links Misbehaving on Some Android Devices

### ISSUE THREAD

**Issue by tpreusse** [orbiting/app#165]
## Bug Report

We received numerous reports that link to not open correctly.

During beta testing we noticed a misconfiguration and were able to fix it:
https://github.com/orbiting/app/commit/5507cf2b4765f85b4e23527e1148b2d0af9884e0

However similar behaviour still seems to happen. Maybe related to some specific mail app. To be investigated!

Raw report:

> Android 6.0 auf einem Acer Liquid plus. [...] Ich habe unterdessen beobachtet, dass der "Link" dazu zwar geöffnet wird, aber die aktuelle Seite (aktueller Artikel) diese gleich wieder überdeckt.

> bei mir passiert heute etwas ganz Seltsames, wenn ich aus dem Newsletter die einzelnen Artikel öffnen will: Ich werde auf falsche Artikel geleitet, jedoch nicht immer auf die gleichen. Wenn ich beispielsweise auf den Link zum Carlos-Artikel klicke, gelange ich einmal auf den Feed, einmal auf "die Republik vorgelesen", einmal auf den Obuchow-Artikel. So geschehen auf dem Android-Smartphone.

> Seit ich die Republik App herunter geladen habe, lande ich bei jedem Klick auf einem im Newsletter verlinkten Artikel im gleichen Artikel. Den Artikel über die Lehman Brothers. Als ich die App noch nicht runter geladen hatte, hat das mit den Links gut geklappt. Es sieht so aus, als ob sich die App immer den ersten Artikel gemerkt hat, den ich in der App gelesen habe. Ich vermute nicht, das es an den > Links im Newsletter liegt sondern an der App.

**Steps to Reproduce**

> Zum nachstellen
> 1. App auf Handy runter laden
> 2. Newsletter in Web.de Email Account öffnen
> 3. Link klicken (am besten mehrere, da es beim ersten Mal geklappt hat)

*from a customer*

We're so far unable to reproduce with Nexus phones we have at the office (GMail + App).

**Actual Results**

Opens last link or in wrong app instance.

**Expected Results**

Open link in the one and only app instance.

**Environment**

- Republik App 1.0.2 / Android 8.0.0 (Samsung SM-A320FL)
- Android 7.0.0 (HTC One $2)

**Comment by jstudach** [comment]
>>> immer wenn ich auf meinem Android 9 Gerät einen Link zu einem Beitrag der Republik öffne, öffnet sich die App mit dem zuletzt gelesenen Inhalt, nicht mit dem des Links. Macht man das dann ein zweites mal dann geht es natürlich.

**Comment by tpreusse** [comment]
@jstudach do you in which app this user clicks republik.ch links? E.g. Gmail-App, Samsung Browser, Evernote, etc.

**Comment by jstudach** [comment]
@tpreusse no. sadly, the information above is all i have.

**Comment by lwihler** [comment]
I've got the same issue with my Sony Xperia XZ1, G8341, Android 8.0

**Comment by tpreusse** [comment]
@lwihler finally someone internal that we can test with! @garamond will probably approach you to test on your device

**Comment by garamond** [comment]
https://github.com/orbiting/app/pull/175
