### ISSUE TITLE
Voice Over does not Work on iOS

### ISSUE THREAD

**Issue by tpreusse** [orbiting/app#167]
## Bug Report

- the wkwebview seems complete inaccessible to voice over.

**Steps to Reproduce**

- turn on voice over
- lunch Republik app

**Actual Results**

- reads nothing, or just the date

**Expected Results**

- as accessible as the website in safari

**Environment**

- OS: iOS 12
- App Version: 1.0.1

**Possible Solutions**

- [RN `accessible`](https://facebook.github.io/react-native/docs/accessibility)
- [iOS `isAccessibilityElement`](https://developer.apple.com/documentation/objectivec/nsobject/1615141-isaccessibilityelement)

**Comment by patrickvenetz** [comment]
Workaround: Voice Over features may be usable on website.

**Comment by schucan** [comment]
Hallo Ihr Lieben

Das funktioniert jetzt!

Keine Ahnung, ob Ihr was getan habt, oder ob das eine Änderung bei iOS war.

Jedenfalls kann von mir aus dieser Bug als gefixt geschlossen werden.

**Comment by tpreusse** [comment]
> Als stark sehbehinderte Person bin ich auf Sprachausgabe angewiesen, um längere Artikel zu lesen.
Gerade auf dem IPhone ist Eure Zugänglichkeit nicht gut und wäre mit einigen wenigen Kniffs einfach zu korrigieren.
z.B. wird manchmal die englische Tastatur verwendet und dann liest das Voice Over die deutschen Texte mit englischer Aussprache.

**Comment by ovbm** [comment]
Getestet in 2.0.0 - es funktioniert.
Das Problem mit der englischen Tastatur konnte ich nicht reproduzieren.

Beobachtungen:
- Bei Inline-Bildern wird der CDN filename vorgelesen
- Bei der Action-Bar wird jeder Button vorgelesen (kann durch swipe übersprungen werden, aber ist mühsam)
