### ISSUE TITLE
fix iOS localizations language indication

### ISSUE THREAD

**Issue by patte** [orbiting/app#174]
The AppStore indicates the App's language as: English.
https://itunes.apple.com/ch/app/republik/id1392772910?mt=8

I checked all the settings in AppStoreConnect only to find that all Language-Choosers are correctly set to "Deutsch". The indication in the AppStore comes from the uploaded bundle tough.

It might be enough to just rename the folder of the localizations to "de" here: https://github.com/orbiting/app/tree/master/ios/Settings.bundle

details of the uploaded bundle:
![screenshot from 2018-11-30 14-00-08](https://user-images.githubusercontent.com/3500621/49292617-10508780-f4ae-11e8-85c0-0f5ccc54c31e.png)

**Comment by tpreusse** [comment]
@garamond please try renaming the localization folder as Patte suggested.
