### ISSUE TITLE
Android: Back button sometimes closes app instead of going "back"

### ISSUE THREAD

**Issue by tobiaslangner** [orbiting/app#177]
## Bug Report

The back button in the Android app sometimes closes app instead of going "back"

**Steps to Reproduce**

1. Start the App
2. Open an article
3. Close the app and terminate the background process (not sure whether this corresponds to onStop() or onDestroy() in the lifecycle)
4. reopen the app, which shows the previously opened article
5. press "back" button

**Actual Results**

app is closed

**Expected Results**

app goes back to main view

**Environment**

- OS: Android 8.0
- App Version: 12.12.2018

**Possible Solutions**

1. If the Back stack is empty and the user is not viewing the main page, go back to the section page and then the main page when pressing back and only then close the app.
2. Ask whether the app really should be closed before doing it.
3. Persist the Back stack when the app is stopped/destroyed.

**Comment by ovbm** [comment]
Should be fixed via 2.0.0, in google play store review.
