### ISSUE TITLE
Draft comment gone when markdown reference or etiquette link clicked

### ISSUE THREAD

**Issue by patrickvenetz** [orbiting/app#183]
## Bug Report

Opening markdown reference or etiquette (below comment input box) opens new browser window. 

Then:
1. Returning from browser window shows either page is also loaded in app.
2. Returning to previous page in app will have comment input box closed and drafted but not submitted contents are gone.

**Steps to Reproduce**

1. Open Dialog and click on a comment
2. Click "respond" icon, arrow pointing left-side underneath comment
3. Click onto markdown reference icon, green box icon labeled **"M⬇️"**

**Actual Results**

Opens browser window.

If page is opened in app, returning to previous view will have input field closed and draft comment is gone.

**Expected Results**

I can return from markdown reference or etiquette page and draft comment in input field is kept.

**Environment**

- OS: iOS 12.1.4
- App Version: 1.0.1, build 44

**Possible Solutions**

- Hinder app to open markdown reference or etiquette in browser window. (Might be caused due to `target=_blank`.) Maybe show markdown reference or etiquette in overlay-esque window (:-1:), or open inside app, being able to go back (👍).
- Keep draft comment in input field on a local device level (local storage). Keep last 10 draft comments (LRU cache pattern). Identify comments via parent comment ID. Remove draft comment once submitted.

«Make it work like on GitHub»

Relates to https://github.com/orbiting/republik-frontend/issues/268

**Comment by tpreusse** [comment]
Alternative solution: open those pages in a modal https://github.com/orbiting/republik-frontend/issues/249

**Comment by tpreusse** [comment]
Solved in the meantime in the frontend by saving comment drafts in local storage.
