### ISSUE TITLE
Back-Button on iPad Pro 12.9“

### ISSUE THREAD

**Issue by philippvonessen** [orbiting/app#187]
## Bug Report

Back-Button nicht vorhanden

**Steps to Reproduce / Actual Results / Expected Results**

**Environment**

Mir ist heute aufgefallen, dass in der App auf dem grossen 12.9 Zoll iPad 
die Zurück-Funktion fehlt.
Auf dem iPhone und dem kleineren 11 Zoll iPad ist die Zurück-Funktion, durch 
einen kleiner als Pfeil sichtbar, in der linken oberen Ecke verfügbar, auf 
dem grossen iPad ist dagegen die Mein-Konto-Funktion (als Profilbild) aktiv.
Dadurch wird die Navigation innerhalb der App verunmöglicht.
Ich freue mich auf eine aktualisierte Version...

App Version 1.0.1
iOS 12.1.4 (iPad)
User:
https://admin.republik.ch/users/5b2e5817-f176-4e50-82bc-116948cf2a62?section=sessions

**Possible Solutions**

**Comment by tpreusse** [comment]
A fix was just rolled out barely 2 years later ;) The issue arose because Apple purposefully made iPad Pros pretend to be Macs, preventing our app from properly detecting it as an iOS device. We now account for this shenanigan. 

Thank you for reporting @philippvonessen.
