### ISSUE TITLE
iPad: Magazin Front nach rechts scrollbar

### ISSUE THREAD

**Issue by lwihler** [orbiting/app#195]
## Bug Report

In der App auf der Front lässt sich das Magazin nicht nur nach oben und unten scrollen, sondern auch nach rechts, wo dann ein weisser Rand zu sehen ist. 

**Steps to Reproduce**

iPad hervornehmen, App öffnen, auf Magazin Front gehen.
(Das iPad wird senkrecht gehalten, die kurze Seite zeigt nach unten). 
Dann scrollt man runter, und nach rechts -> Magazin verschiebt sich nach rechts, wackelt hin und her.

**Actual Results**

![](https://media.giphy.com/media/cLSRQ85PCLuwmDpT4l/giphy.gif)

**Expected Results**

Die Ansicht lässt sich nur nach unten scrollen, aber nicht nach links oder rechts.

**Environment**

- OS:  iOS 12.2, (iPad)
- App Version:  1.1.1 

(aktualisiert)

**Comment by tpreusse** [comment]
Ursache ist ein zu fettes Wort («Verantwortlichen») ohne weiches Trennzeichen. Fix kommt mit der morgigen Front.
