### ISSUE TITLE
User kann sich nicht mehr einloggen nach dem Löschen des App-Caches

### ISSUE THREAD

**Issue by Murr2016** [orbiting/app#196]
## Bug Report
User meldet, nach dem Löschen des App-Caches, konnte er sich nicht mehr in der App einloggen. Fehlermeldung: «Anmeldung mit der App können nur von der Benutzerin selbst zugelassen werden.»

Session serverseitig zu löschen, hat den Fehler behoben. 

**Steps to Reproduce**

https://admin.republik.ch/users/14bc77ac-a56a-4add-9b43-c4349832c585

**Actual Results**

**Expected Results**

**Environment**
Android 8.0
App Version: 1.1

**Possible Solutions**

**Comment by tpreusse** [comment]
In so einem Fall muss man die Anmeldung per E-Mail bestätigen. Obwohl die Notifications noch ankommen.

Grund: Cookie wurde gelöscht und wir können nicht mehr prüfen ob das Gerät Anmeldungen bestätigen darf. Notifications kommen noch an da selbes Gerät mit dem selben Google Konto für uns ist dies aber nicht überprüfbar.

Allgemein sollten wir uns wohl überlegen aus der App raus immer per E-Mail bestätigen lassen. Mit einer App, eine andere App zu autorisieren ist wohl eher ein Edge-Case. Wenn man sein Tablet auch einmal per E-Mail bestätigen muss ist dies ja auch nicht weiter schlimm.

**Comment by tpreusse** [comment]
Inzwischen sendet das Backend an App User immer eine E-Mail.
