### ISSUE TITLE
Universal Linking Issues

### ISSUE THREAD

**Issue by tpreusse** [orbiting/app#199]
## iOS issues

> Wenn die Republik-App länger nicht verwendet wurde, wird beim Öffnen von Push-Benachrichtigungen nur die Hauptseite geladen. Der Kommentar wird nicht angezeigt und muss selbst gesucht werden.
[](https://www.republik.ch/dialog?t=general&focus=3a898b38-2469-42af-a34b-acd840772efc)

> after not using the app for a while url from push notifications do not open correctly

[Source](https://www.republik.ch/dialog?t=general&focus=3a898b38-2469-42af-a34b-acd840772efc), iPhone SE, iOS 12.4, App Version: 1.1.1

## Android issues

We've heard that universal link opening on Samsung devices always fails the first time. We were able to reproduce it on colleagues devices but always worked correctly on the Nexus devices we have for development.

**Comment by jstudach** [comment]
Similar Problem:

> In letzter Zeit fällt mir auf, dass, wenn ich im Newsletter auf Links klicke, die App zwar öffnet, aber immer auf der Seite, wo ich zuletzt war, anstatt auf dem verlinkten Artikel.
> 
> iOS wie App sind auf dem neuesten Stand.

**Comment by lwihler** [comment]
Weitere Meldung diesbezüglich

> Wenn mein iOS R App noch auf einem Beitrag ist und ich vom Email in die App gelinkt werde, funktioniert das Laden innerhalb der App erst, wenn die App auf der Homescreen ist. Ich muss also R-Homescreendrücken-zurückinsEmail-nochmalsLinkdrücken.
