### ISSUE TITLE
webview

### ISSUE THREAD

**Issue by patte** [orbiting/app#2]
- [x] persist webview context (cookies, localStorage) to app (backuped) storage
- [x] link handling
  - [x] external links open in system browser
  - [x] internal links
    - normal redirect in app
    - special republik.ch addresses must open in system browser
      - republik.ch/anmelden
      - republik.ch/angebote

**Comment by diegomura** [comment]
Android does not support excluding specific URLs from deeplinking, so we will need to eventually see if there is a workaround for this. For iOS you configure that from the `apple-app-site-association`. There is a WIP in #4

**Comment by diegomura** [comment]
@patte if we let `/anmelden` to be opened by the native browser, the user should never be able to request login from within the app. Changes [here](https://github.com/orbiting/app/compare/auth...routes-on-native-browser?expand=1#diff-576cd6654e3bed017c8982f4a4560a25R12). What's the exact behavior we want for that route?
