### ISSUE TITLE
Bug: Links do not open in App (iOS 13)

### ISSUE THREAD

**Issue by jstudach** [orbiting/app#202]
Article-Links from the Newsletters do not open in the R-App in iOS 13.

"Habe mir gestern iOS 13 auf dem iPhone installiert. Seither wird Safari geöffnet, wenn ich im Newsletter auf einen Artikel-Link tippe. Früher sprang der Link jeweils direkt in die App. 

Muss ich was ändern damit das wieder funktioniert, müsst ihr was ändern, oder ist das ein Akt Apples?"

**Comment by ovbm** [comment]
Sollte mit 2.0.0 behoben sein. Wenn nicht gerne melden.
