### ISSUE TITLE
Test Parcours

### ISSUE THREAD

**Issue by ovbm** [orbiting/app#229]
CAVEAT: Notifications can only be properly tested once a beta version is released which used the production frontend (requires https://github.com/orbiting/republik-frontend/pull/515 to be merged).

How to: Copy the List below and paste it into a comment. State your device & OS and go through the list. If you find anything else, post it as a comment.

**StartUp**
- [ ] Startup, check that Splashscreen reacts to the phone's theme (dark/light)
- [ ] Check if setting Nightmode to "automatic" works. (switch phone theme and see if changes work)

**Login**
- [ ] Log in to the App
- [ ] Log in to Republik.ch on the web and confirm login with App (should spawn notification)
- [ ] Upload a new profile picture

**Notifications**
- [ ] Check notification reception
- [ ] Check that clicking on notification navigates to the appropriate place

**Audio Player**
- [ ] Launch Audioplayer in App
- [ ] Control Audioplayer in App (start, stop, skip forward backward, close, reopen, pan progress)
- [ ] Control Audio from control panel
- [ ] Launch Audioplayer in web and skip to a certain position. Let play for 5 sec. Open same audio in app and check if progress is preserved. (and vice versa)
- [ ] Click on Audio Title and check if it navigates to the document
- [ ] Check if margins of audioplayer look correct

**Other**
- [ ] Check if video playback works as expected (inline & fullscreen or external (filmingo))
- [ ] Android: Check if scrollbar is visible on Android in darkmode
- [ ] Open a gallery image and check that the status bar disappears and changes color

**Old Bugs (optional, will be checked by @ovbm)**
- [ ] Android: Check if back buttons issues are fixed  #177 , #190 
- [ ] Check if #187 is fixed

**Comment by tpreusse** [comment]
It's soo nice to finally have proper dark mode in the app 🎉 

Most things worked as expected. But here 8 things I noticed while testing:

1. scrolling feels wrong, is inertia scrolling disabled on the web view?
2. audio controls in control center (outside of app) does not work: play/pause/15 back and forward just does nothing. Btw why 15 forward and not 30 like in app and Podcast app in control center?
3. audio controls in app work, 10 back and 30 forward feel sluggish – take a while to update time stamp, btw why not back 15 like Apple Podcast App?
4. choosing a different audio also updates the time sluggishly, keeps old current time around / displayed for a few seconds 
5. notifications to article urls work, notifications to debate comments lead to the right debate but with a comment not found error, probably the [`?t=`](https://github.com/orbiting/app/blob/53d8e0e8b2e1579919fdc358077ffde8da29cd7a/src/screens/Web.js#L59) suffix workaround breaks the query string, maybe try `#app-load-${uuidv4()}` instead
6. when rotating phone in dark mode a while background becomes visible behind web view and audio player
8. in landscape mode the status bar disappears as expected but the area of the status bar remains
![IMG_4115](https://user-images.githubusercontent.com/410211/104650358-5da40900-56b6-11eb-9f01-09aa8cbfcde1.PNG)
9. the filmingo dynamic component shows an error (works in old app)
![IMG_4116](https://user-images.githubusercontent.com/410211/104650664-d30fd980-56b6-11eb-9187-7684a6a141db.PNG)

**Comment by ovbm** [comment]
Thanks!!!

1. `decelerationRate` is not explicitly set, so it should be iOS standard "fast". I've now set it to "normal", so it should flow a bit more -> next release.
2. Forgot to implement remote controls, will do so asap -> next release. 
3. The 10sec I chose because react-icons doesn't have a back 15 sec icon 🤪, custom icons are a pain in react-native...as it doesn't support SVG out of the box. Stupid reason, I know, but if you find it unbearable, I can try to change it.
4. Maybe we'll figure out why the audio player is sluggish on code review?
5. Don't understand` #app-load-${uuidv4()} `, let's sync for this.
6. Got it! will check what that white flash is. -> next release
7. On it -> next release
8. Same. -> next release

**Comment by patrickvenetz** [comment]
**Flight mode**

_Expected:_ App will tell me, if it can't connect to Republik servers.
_Actual:_ App displays "Network fetch failed". Pull-to-refresh then leads to blank screen I can not escape from.

Steps to reproduce:
- Open app, load article
- Set phone into flight mode
- Navigate to feed

(Version 2.0.6, Android 11 on Pixel 4)

**Comment by patrickvenetz** [comment]
**Automatic dark mode**

_Expected:_ App is rendered in dark mode when dark mode is enabled
_Actual:_ App is not rendered in dark mode

Steps to reproduce:
- Open app, set dark mode to "automatic"
- Force phone into dark mode
- Return to app

(Version 2.0.6, Android 11 on Pixel 4)

**Comment by patrickvenetz** [comment]
**Audio player: Stop not working**

_Expected:_ Clicking stop on Android provided audio player interface in notification bar will stop audio
_Actual:_ Click has no effect

Steps to reproduce:
- Open app, play audio
- Pull down Android notification bar and click on stop icon

(Version 2.0.6, Android 11 on Pixel 4)

**Comment by patrickvenetz** [comment]
**Audio player: Click in notification bar player opens blank page**

_Expected:_ Click on Android provided audio player interface in notification bar will open article or audio player in Republik app
_Actual:_ App opens and renders blank page. (I can navigate to previous screen.)

(Version 2.0.6, Android 11 on Pixel 4)

**Comment by patrickvenetz** [comment]
**Audio player: Not resuming previous position**

_Expected:_ Playing a previously listened to audio article, it forwards to last known position.
_Actulal:_ Starts from begining

(Version 2.0.6, Android 11 on Pixel 4)

**Comment by patrickvenetz** [comment]
**Link long-hold**

Expected: App shows context menu on what to with link.
Actual: App does nothing but briefly vibrate.

Steps to reproduce:
- Open app, load article with links
- Tap-and-hold link for a while

(Version 2.0.8, Android 11 on Pixel 4)

**Comment by ovbm** [comment]
> **Unexpected link tap-and-hold behaviour**
> 
> _Expected:_ App shows context menu on what to with link.
> _Actual:_ App does nothing but briefly vibrate.
> 
> Steps to reproduce:
> 
> * Open app, load article with links
> * Tap-and-hold link for a while
> 
> (Version 2.0.8, Android 11 on Pixel 4)

I don't think the old app was able to show link previews on link hold. At least it's not something the webview component supports for android. There's a flag allowsLinkPreview, but it's only for iOS.

**Comment by fuenkchen** [comment]
**Automatic Dark mode not working on Android**

_Expected_: App switches to dark mode if set to automatic and system is changed to dark mode
_Actual_: App shows dark mode splash screen when opening the app, but header and articles remain in light mode (it works in browser though)

Steps to reproduce:
- Set dark mode to automatic
- Change system setting to dark mode
- Open app again

Version 2.0.8, Android 10 on Sony Xperia 1

**Comment by fuenkchen** [comment]
**Android back button not working**

_Expected_: Using Android's system back button navigates back to previous page (article, front page, etc.)
_Actual_: Using Android's system back button closes app

Steps to reproduce:
- Open app
- Navigate to at least two articles
- Try to go back with Android's go back button

Version 2.0.8, Android 10 on Sony Xperia 1

**Comment by fuenkchen** [comment]
**Scrollbar not visible on light background**

_Expected_: When reading/scrolling down an article I should see a scrollbar
_Actual_: Scrollbar is only visible on dark backgrounds (in dark mode or on dark pages like dokdown articles)

Steps to reproduce:
- Open app in light mode
- Scroll through an article

Version 2.0.8, Android 10 on Sony Xperia 1

**Comment by ovbm** [comment]
Some observations regarding the issue where a dialog discussion entry isn't fond. It could be that it always happens only if the entry is the latest entry added... it doesn't seem to happen when opening older notifications

e.g.
https://ux.republik.ch/dialog?t=general&focus=048391ba-f721-4c57-abb4-99a39a3e2f8c

**Comment by ovbm** [comment]
**Infinite loading when clicking on AudioPlayer Title**
Expected: When clicking on the title in the audioplayer, while I'm already in the article of said audio file, I expect either to reload to the same page or for nothing to happen at all.
Actual: Loading animation starts but never stops.

Steps to reproduce
- Open any audio-file from within an article
- Stay on that site
- Click on title

version 2.0.10 iOS

**Comment by ovbm** [comment]
Filmingo doesn't play in app

Expected: When clicking on filmingo, I expect to stay in the app
Actual: Scrollbar is only visible on dark backgrounds (in dark mode or on dark pages like dokdown articles)

Steps to reproduce:

Open app in light mode
Scroll through an article
Version 2.0.8, Android 10 on Sony Xperia 1

**Comment by fuenkchen** [comment]
**Closing app with running audio player leads to problem when trying to start app again**

_Expected_: App navigates to last visited article and displays audio player (with last listening position), i.e. it behaves as if audio player would have paused before closing the app
_Actual_: App keeps stuck in splashscreen when opening again after closing it with running audio player. 

Steps to reproduce:
- Open app
- Navigate to article with audio content
- Start audio
- Close app without pressing pause in audio player
- Open app again 

Version 2.0.0, Android 10 on Sony Xperia 1
