### ISSUE TITLE
Android back button in article view always jumps to top of article list

### ISSUE THREAD

**Issue by tobiaslangner** [orbiting/app#252]
## Bug Report

When pressing back to return from the article view to the article list, the list always scrolls to the top to the newest article instead of remembering the position from where the article was clicked. This is very annoying in particular when browsing and reading through older articles, since after reading an article, one has to scroll all the way down to the old position over and over again.

**Steps to Reproduce**

1. Open the Republik App
2. Click on the Republik logo on the top to navigate to the article overview
3. Scroll down a few pages and click on any article.
4. Press the back button

**Actual Results**

The article list has been scrolled to the top, showing the most recent published article.

**Expected Results**

The article list remains at the position from where I had clicked the article, so that I can continue browsing from the same position, instead of having to manually scroll all the way down again.

**Environment**

- OS: Android 10
- App Version:most recent version as of 31/03/2021, could not find the actual version.

**Comment by tpreusse** [comment]
Hello Tobias

Thank you for the report. We had to implement a custom back logic on Android in order to decide when to close the app when pressing the native back button. Unfortunately our current custom implementation does not support preserving scroll  positions, we'll try to improve this with the next update and shall notify you once we have done so.

**Comment by tobiaslangner** [comment]
It's been two months since the last update, could you please comment on whether something has happened? This bug makes the app almost unusable for me (I now resorted to using the browser again) so I think it is important to get it fixed...

**Comment by tpreusse** [comment]
Unfortunately we haven't been able to work on this yet—it didn't make it into the spring update. Hopefully we'll manage to do an update with a fix this summer or early fall.

I'll also try to explore a quick fix without an app update. Maybe on option would be to temporarily also display a back button in the header like on iOS:
<img src="https://user-images.githubusercontent.com/410211/120778814-d05b3700-c526-11eb-9103-7335c98ebc68.PNG" width="320" />
