### ISSUE TITLE
universal/app links

### ISSUE THREAD

**Issue by patte** [orbiting/app#4]
- [x] the app registers itself to handle our urls: http(s)://(www.)republik.ch*
  - for iOS see: https://developer.apple.com/library/content/documentation/General/Conceptual/AppSearch/UniversalLinks.html
  - for android see: https://developer.android.com/training/app-links/
  - see [webview issue](https://github.com/orbiting/app/issues/2): certain paths must open in system browser - if possible they should be excluded from opening in the app.

**Comment by diegomura** [comment]
Once I have a Republik developer account (#13), I can have a staging app ID to start testing universal linking. WIP in #14

`apple-app-site-association` file
```json
{
    "applinks": {
        "apps": [],
        "details": [
            {
                "appID": "", // TBD
                "paths": [ "NOT /anmelden", "NOT /angebote", "*" ]
            }
        ]
    }
}
```
