### ISSUE TITLE
Document used WebView/Browser Engines

### ISSUE THREAD

**Issue by diegomura** [orbiting/app#40]

**Comment by diegomura** [comment]
It seems that `android.webkit.WebView` is the only Android implementation for a web view.

> Since Android 4.4 (KitKat), the WebView component is based on the Chromium open source project. WebViews now include an updated version of the V8 JavaScript engine and support for modern web standards previously missing in old WebViews. New Webviews also share the same rendering engine as Chrome for Android, so rendering should be much more consistent between the WebView and Chrome. [Source](https://developer.chrome.com/multidevice/webview/overview)

However, depending on which Android version you're running, the Chrome version the WebView is based on.

**Comment by patte** [comment]
Is it possible to send the "real" user-agent instead of "RepublikApp". If so I would like to change the user-agent to: "${userAgent} RepublikApp". So we always know what versions of the webviews are running.

**Comment by patte** [comment]
I think reporting the version via `user-agent` solves this issue, really nice!
For the documentations sake:
- ios: `Mozilla/5.0 (iPhone; CPU iPhone OS 11_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15G77 RepublikApp`
- android: `Mozilla/5.0 (Linux; Android 5.1; HUAWEI LYO-L01 Build/HUAWEILYO-L01; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/67.0.3396.87 Mobile Safari/537.36 RepublikApp`

**Comment by patte** [comment]
@diegomura could you also add the app version? just before `RepublikApp` is would propose...

**Comment by diegomura** [comment]
No problem!
`RepublikApp/0.1.0` is good for me if that does not break anything on the backend
