### ISSUE TITLE
Cookie expiration

### ISSUE THREAD

**Issue by diegomura** [orbiting/app#46]
Test how app behaves when session cookie expires. We can easily test this locally by editing the cookie TTL

**Comment by diegomura** [comment]
(A) When I delete current session from database and then click in app into "Konto" I _expect_ it to report something along the way that I've been logged out or session did expire. _Currently_ it shows me a blank screen. Then clicking onto "REPUBLIK" button shows sign-in screen but profile pic remains in header. (Android 8.1.0, Nexus 5X, App 0.0.7)

(B) When signing in state as described in (A) it does display message about verifying email but then black screen with "Die App kommt, wenn Sie fertig ist" ("App is coming, when you is done") appears and I did not get a verficiation link. (Android 8.1.0, Nexus 5X, App 0.0.7)
When I am on "Datenschutz" page ("Privacy") while clicking onto a verification link, I _currently_ don't see that I am logged in until I click onto the "REPUBLIK" button but I'd _expect_ at least to profile pic top left to change which it does not. (Android 8.1.0, Nexus 5X, App 0.0.7)

**Comment by diegomura** [comment]
I could verify point A. This happens because currently the app does not have any way of verifying that the session was deleted or expired. The only way I can know this is by the `me` query, but this is already cached the moment the session expired, so the app never finds out that now is `null`.

Or we either change the `me` query on the frontend not to be cached, or we consume this endpoint directly from the app every certain time (or on each url change or similar) to be able to act when `me` changes.

cc/ @patte @tpreusse

**Comment by patte** [comment]
I don't quite understand. Should me not be cleared from the cached if it's requested unauthorized? Yes it's cached, but it should go away as soon as the session expires, or do I not understand something?

**Comment by diegomura** [comment]
Maybe I'm wrong about the cache.
What I see is that after the user logs in, the frontend never ask the app to resolve the `me` query again (because it's cached), not even after I delete the session. This causes the app to never find out the user is not logged in anymore and never trigger the [logout callback](https://github.com/orbiting/app/blob/master/src/screens/Web.js#L182). That's why the app still shows the user avatar after user logout

**Comment by patte** [comment]
see: https://github.com/orbiting/app/pull/106

**Comment by diegomura** [comment]
@patte  Should be fixed now, but not closing this issue until you verify in your end that it's working as expected

**Comment by patte** [comment]
I din't find a way to get into the inconsistent state :+1:
