### ISSUE TITLE
Manifest page

### ISSUE THREAD

**Issue by diegomura** [orbiting/app#58]
Two main issues:
- Manifest page has a `target=_blank` link, which forces the page to be opened in a new browser window in iOS
- There's no menu in manifest, so the header buttons become useless. It's unclear yet what we should do with them

**Comment by patte** [comment]
- showing it in the app would mean, we need to hide the header (the big R and the header don't look good)
- hiding the header means there is no back button anymore.

I think it's totally ok how it is
