### ISSUE TITLE
App can be used offline

### ISSUE THREAD

**Issue by patte** [orbiting/app#6]
- [ ] research offline strategies
  - [ ] next export & OTA updates?
  - [ ] ttl cache in apollo?
  - [ ] service workers via [next-offline](https://github.com/hanford/next-offline)?

**Comment by lwihler** [comment]
Idee für Umsetzung:
Offline-Modus an Merkliste knüpfen.

Alle Artikel, die auf der Merkliste sind, werden heruntergeladen und sind offline verfügbar. 

Wenn man den Artikel dann nicht mehr will, kann man den Pfeil wieder deaktivieren, was den Artikel aus dem Speicher löscht.

**Comment by zwetschgenmus** [comment]
Bei einer WiFi verbindung kann alles geladen werden. Bei einer Mobilverbindung nicht unbedingt. Heisst, bei Wifi wuerd ich allenfalls konfigurierbar, oder freigebbar den gesammten Content laden. Falls Weitergabe ein Thema ist, individuell verschlüsselt.

**Comment by gvainfo** [comment]
Wenn ich die Doku richtig verstehe, benutzt Ihr die App heute nur als "anderes" Frontend für die Website. 

Offline-Nutzung setzt voraus, dass der Content lokal gespeichert wird.

(1) Wie weiss die App, dass es neuen Content gibt?
- Die App könnte regelmässig eine Referenzinformation abrufen, die ihr erlaubt, den Stand ihres Wissens mit dem Stand der Republik zu vergleichen (https://republik.ch/lastupdate liefert 20191130103245) -> habe ich einen geringeren Wert, sollte ich updaten
- Die App wird über den Push-Channel (den ich nicht kenne) über ein Update informiert

(2) Wie weiss die App, welcher Content neu ist?
Die App benötigt eine Datenbank (Datei oder sqlite), in der der Index vorgehalten wird. Als eindeutiger Identifier reicht die URL des Artikels, mit dem letzten Änderungsdatum. Dazu benötigt die App noch das Datum der Veröffentlichung für (4).

(3) Die App hat "entdeckt", dass es neuen Content gibt
Die App lädt den neuen Content herunter und speichert ihn entweder im Dateisystem oder in einer sqlite-DB; bei Bildern, Videos und Audio-Dateien ist das Dateisystem vermutlich besser geeignet.

(4) Wann löscht die App Content?
Der Benutzer kann konfigurieren, wie viele Monate/Tage der Content vorgehalten werden soll. Content, der älter als n Tage ist, wird gelöscht.

Das wäre die "do-it-yourself"-Lösung mit REST.

Man könnte auch einen Messaging-Bus benutzen (zum Beispiel https://www.rabbitmq.com/tutorials/tutorial-three-javascript.html), der neuen Content verteilt.

Housekeeping müsste bleiben.

Ein Ansatz könnte sein, sich zu überlegen, ob beim Abruf des Feeds zuerst lokal geschaut wird, ob die Datei auf dem Dateisystem (cache) in einer aktuellen Version vorhanden ist; dann wäre die URI eben nicht http(s), sondern file://.

Danach wäre ein simpler Weg, einen speziellen Feed für die App zu erzeugen, der wiederum "file://"-URIs enthält und keine http://-Uris.

Wenn man das macht, könnte man zum Beispiel auch in das Dateisystem synch'en, über einen der oben beschriebenen Mechanismen.

Vielleicht inspiriert das eine oder andere Euch :)

**Comment by ovbm** [comment]
See discussion for further development: #244
