### ISSUE TITLE
Upload profile picture form not working on android

### ISSUE THREAD

**Issue by diegomura** [orbiting/app#62]
Researching, I found that react-native standard webview implementation does not tupport html file inputs:

- https://github.com/facebook/react-native/pull/12807
- https://github.com/facebook/react-native/issues/11230

If you read those threads, you will see that the core team has no intention of solving this. This is an issue plenty of people had, so many libraries were created:

- https://github.com/lucasferreira/react-native-webview-android
- https://github.com/dongyaQin/react-native-webview-file-upload
- https://github.com/Oblongmana/react-native-webview-file-upload-android
- https://github.com/andreipfeiffer/react-native-webview-android-file-upload
- https://github.com/martinarroyo/react-native-webview-file-upload

Some of these are forks from another. @patte @tpreusse I would like to hear your thoughts on this. I'' test them and see how they work, but the major downside of using one of these is that they are quite experimental, and can be outdated, making other features not to work and hard to debug eventually

**Comment by danaee123** [comment]
?
