### ISSUE TITLE
Some images are not being loaded in iOS webview 

### ISSUE THREAD

**Issue by diegomura** [orbiting/app#68]

**Comment by diegomura** [comment]
hey @patrickvenetz !
I'm not sure the current state of this issue, but I don't think I saw this happening for awhile now. Do you have any update?

**Comment by patte** [comment]
@patrickvenetz suspicion was webp. I tested this and can confirm that webp detection works as expected. Closing for now, as it might have had something to do with the staging setup and not with the app.
