### ISSUE TITLE
Clear webview history after login and logout

### ISSUE THREAD

**Issue by diegomura** [orbiting/app#86]

**Comment by diegomura** [comment]
This is not possible from the react-native webview's API.
I'll keep this issue open for further discussion

**Comment by diegomura** [comment]
Ok. So I dig a bit on this today in here https://github.com/orbiting/app/tree/clear-history
For sure it would require native code, but even with this I couldn't make it work on Android. iOS seems even more hacky, since there's no method you can call on the view to do this. Solutions varies (without a reported working solution), going from instantiating the internal webview again, to extending the webview element. 

The only moment in which this can be needed is after the user login, but it's an edge case, and if this happens, you can click on the logo and go back to the front.

IMO implementing this can interfer with the WebView normal behaviour, causing future bugs.

**Comment by tpreusse** [comment]
Doing a hard re-load after sign in/out seems to do the trick.
