### ISSUE TITLE
Reload webview when coming from background (if online)

### ISSUE THREAD

**Issue by patte** [orbiting/app#91]
When the app comes from background it should check if there is internet connection available and if so, reload the webview, so the most recent version of the republik.ch is shown.
Bonus: only refresh the apollo queries instead of reloading the webpage completely. Totally bonus tough, as I don't know how hard/practical that is.

**Comment by patte** [comment]
While testing many criticized that the app reloads every time it comes to foreground. When thinking about it, @tpreusse came up with the good idea, that the app should only reload the webview if
- we have internet connection
- AND the user navigates to a overview page (front, feed, feuilleton)

This would allow to immediately continue reading an article when coming from the background without loosing the previous scroll position. And only bother the user with waiting time where things might actually have changed (articles almost never update).

BONUS: instead of reloading the webview it would be faster to just refetch the queries on the overview pages. Or is this a bad idea?

@tpreusse Did I phrase your idea correctly?

**Comment by tpreusse** [comment]
No, what I had in mind was a bit different:
When coming into foreground after 1 hour or more and a active internet connection, it should disable client side navigation / hijack it and do a server side navigation instead on the next navigation action.

> BONUS: instead of reloading the webview it would be faster to just refetch the queries on the overview pages. Or is this a bad idea?
An important objective is also to update the frontend version if a new one is available. If anything it should clear the next.js page (aka code) cache. Which will trigger a hard reload if one navigates to a different page. Which then will automatically clear the apollo cache. Clearing and managing outdated apollo cache data should be tackled in a separate issue and not just for the app.

Not sure what is easier to do: clearing next.js page cache or modifying/hijacking `history.pushState`/`history.replaceState` for this (we're already doing something with history right?).

**Comment by diegomura** [comment]
I also find a bit annoying the reloading, so I think doing something about it is a good idea. 
I'll try your approach @tpreusse , but I'm a bit afraid that switching between the navigation hijack back and forth will break things. Having that working was a bit rough. But I'll try and let you know. What we can do if that causes trouble is just forcing the reload when user navigates after 1hr and if has connection. The user experience would be almost the same, but without messing with a quite "fragile" and hacky part of the solution (which we already know it's working fine)

**Comment by diegomura** [comment]
I implemented what I mentioned in the PR above. The result IMO is great. Since we are reloading we even see the native loading spinning wheel, and it does not mess with the low-level navigation hijack logic.

@tpreusse do you see any downside of this?

**Comment by tpreusse** [comment]
@diegomura LGTM, go for it
